### PR TITLE
Changes to support running with usermode runtime, and longer test duration

### LINKED ISSUE #30: Unable to run tests on Usermode Runtime
TwinCAT now supports a "usermode" runtime, which is convenient for unit tests because it works on more development environments (for example on computers with Windows Subsystem for Linux (WSL) or HyperV enabled, where the normal TwinCAT runtime won't work). However the test adapter will require some work to support this.

Attempting to run the tests on usermode runtime currently fails in a few places.

Firstly, the unit tests assume that they are targeting a local AmsNetID. The usermode runtime uses an alternate ID, for example `192.168.4.1.1.1` is default in `C:\TwinCAT\3.1\Runtimes\UmRT_Default\start.bat`. To support running tests against usermode runtime, the net ID needs to be parameterized.

In TestRunner.cs it fails because the usermode runtime route is local but does not show up in the static routes list.
```
if(AmsNetId.LocalHost != target && AmsNetId.Local != target)
{
    var adsRemoteRoutes = TwinCATEnvironment.GetRemoteRoutes();
    var targetRoute = adsRemoteRoutes.Where(r => r.NetId.Equals(target));

    if (!targetRoute.Any())
        throw new Exception("No ADS route to target found.");
}
```

Removing or commenting this section of code allows it to proceed and to connect.

The next place it fails is in TwinCATXAEProject.cs, because it is a default single shared core config, which does not add a <Settings> entry in the tsproj file. Changing as below allows it to proceed:
```
if (realtimeSettings != null)
{
    int.TryParse(realtimeSettings.Attribute("MaxCpus")?.Value, out int maxCpuCount);
    int.TryParse(realtimeSettings.Attribute("NonWinCpus")?.Value, out int isolatedCpuCount);
    var sharedCpuCount = maxCpuCount - isolatedCpuCount;

    RealtimeSettings = new Tuple<int,int>(sharedCpuCount, isolatedCpuCount);
}
// add the section below
else 
{
    RealtimeSettings = new Tuple<int,int>(1, 0);
}
```

Finally, because the boot folder is a different location than default, it fails to find the result file. The easiest work around is to set the xUnitFilePath to `'%TC_BOOTPRJPATH%tcunit_testresults.xml'` as done by @philippleidig in the latest TcUnit version. I went ahead and did this in the PlcTestProject settings in the linked PR.

My use case for using usermode runtime or any alternate runtime is that I cannot run TwinCAT XAR locally, including the tests, because it does not work on newer generations of laptop from Lenovo due to various issues with the hardware. So tests always have to either run against a physical target, this usermode runtime, or in a virtualized environment.

To reproduce this, you can start a new usermode runtime via `C:\TwinCAT\3.1\Runtimes\UmRT_Default\start.bat` and then point the tests to `192.168.4.1.1.1`.

### PR DESCRIPTION
**Pull request by dfreiberger**
This PR adds support for running the tests of VsTestAdapter using the usermode runtime.

It also adds support for specifying longer test durations.

### CODE REVIEW

File: src/TcUnit.TestAdapter/Execution/TestRunner.cs [hunk 1]
```diff
@@ -158,15 +158,7 @@ public TestRun RunTests(TwinCATXAEProject project, IEnumerable<TestCase> tests,
             var target = AmsNetId.Parse(runSettings.Target);
             var cleanUpAfterTestRun = runSettings.CleanUpAfterTestRun;
             var cleanUpBeforeTestRun = true;
-
-            if(AmsNetId.LocalHost != target && AmsNetId.Local != target)
```
Comment (dfreiberger) [inline src/TcUnit.TestAdapter/Execution/TestRunner.cs:162]: Here I am removing this check since the usermode runtime doesn't appear in the list of remote routes, and it does not have a local host net ID.

@philippleidig is this OK or do you have a suggestion on how to handle this?

Comment (philippleidig) [reply src/TcUnit.TestAdapter/Execution/TestRunner.cs:162]: Totally fine for me. To be honest, I don't have any other solution either.
